#---

- hosts: all

  vars:
    ansible_ssh_private_key_file: "{{ lookup ('env', 'SSH_KEYDIR') }}/tlewis_labs_kp.pem"

    rpm_url: "https://pkg.jenkins.io/redhat-stable/jenkins-2.7.4-1.1.noarch.rpm"

  tasks:

    - name: "install jenkins from remote rpm: {{ rpm_url }}"
      yum:
        name:  "{{ rpm_url }}"         
        state: present
      become: true
      become_user: root

    - name: "create jenkins user"
      user: 
        name: jenkins
        comment: "jenkins service user"

      become: true
      become_user: root
      
    - name: "start jenkins service"
      service:
        name: jenkins
        state: started     
      become: true
      become_user: root
 
